# Generated by Django 3.1.7 on 2021-02-21 22:19

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('tags', jsonfield.fields.JSONField(null=True)),
                ('date', models.DateField(blank=True, verbose_name='Date')),
                ('link', models.URLField(blank=True, max_length=500)),
                ('technologies', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTechnologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_project_name', to='portfolio.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_project_name', to='portfolio.project')),
            ],
        ),
    ]
