# Generated by Django 3.1.7 on 2021-02-22 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210221_2105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTechnologies',
        ),
    ]
