# Generated by Django 3.1.7 on 2021-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_delete_projecttechnologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='is_main_image',
            field=models.BooleanField(default=True),
        ),
    ]
