# Generated by Django 3.1.7 on 2021-02-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projectimage_is_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='is_main_image',
            field=models.BooleanField(default=False),
        ),
    ]
